# permissions for end users to edit monitoringapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: monitoringapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-kara
    app.kubernetes.io/part-of: k8s-kara
    app.kubernetes.io/managed-by: kustomize
  name: monitoringapp-editor-role
rules:
- apiGroups:
  - app.kara.com
  resources:
  - monitoringapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.kara.com
  resources:
  - monitoringapps/status
  verbs:
  - get
